[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=CDAD9B9048599A76F0E5B58895BFEA96
ProjectName=Third Person BP Game Template
CopyrightNotice=LeaveMeAlone Game by Netologiya. All RightsReserved.

[StartupActions]
bAddPacks=True
InsertPack=(PackSource="StarterContent.upack",PackName="StarterContent")

[LeaveMeAlone]
;Цели уровня
TotalShields=3
TotalKeyCards=5
RequiredEvacuationTime=5.0

;Ключ-карты
KeyCardTTL=30.0
KeyCardRespawnDelay=15.0
KeyCardStartActiveCount=2

;Выносливость игрока
MaxStamina=80.0
SprintStaminaDrainRate=15.0
StaminaRegenRate=10.0

;Усиленный враг
EnhancedEnemyHealthMultiplier=5.5
EnhancedEnemyDamageMultiplier=5.0
EnhancedEnemySpeedMultiplier=1.3

